export const GET_INVENTORY = 'GET_INVENTORY';
export const REQUEST_INVENTORY = 'REQUEST_INVENTORY';
export const RECEIVE_INVENTORY = 'RECEIVE_INVENTORY';
export const CHANGE_INVENTORY_BAG_R = 'CHANGE_INVENTORY_BAG_R';
export const CHANGE_INVENTORY_USER_R = 'CHANGE_INVENTORY_USER_R';
export const CHANGE_INVENTORY_BAG_L = 'CHANGE_INVENTORY_BAG_L';
export const CHANGE_INVENTORY_USER_L = 'CHANGE_INVENTORY_USER_L';
